### ISSUE TITLE
Improve references to the activity list

### ISSUE THREAD

**Issue by nickevansuk** [cuttlefishers/opendata#1]
This feed is very exciting! Great work getting to this point!

The README says that "The activity lists are published to conform to OpenActive Modelling Opportunity Data", however the activity list references in the feed do not conform with the [OpenActive Activity List](https://www.openactive.io/activity-list/), which makes them difficult for data users to ingest.

SportSuite were one of the original contributors to the OpenActive Activity List, so I'm sure the mapping would be straightforward

See guidance: https://developer.openactive.io/publishing-data/activity-list-references

**Comment by domfennell** [comment]
Hi @RoastVeg,

Very much echo @nickevansuk's excitement. Great to have your data open. Thanks for your efforts.

RE `activity` data, the way this is currently included in the feed is making it difficult for us to use the virtual sessions data. We suggest you map from your feed to the standard activity list, especially given that my understanding is that SportSuite were originally contributors to that list.

Hopefully the OpenActive guidance on this will prove useful: https://developer.openactive.io/publishing-data/activity-list-references.

Thanks in advance,

Dom

**Comment by RoastVeg** [comment]
Our activities conform to an internal list that we maintain, and though we originally contributed to the OpenActive list we have since expanded greatly and adapted upon it. The full content of this list ([SportSuite's A-Z](https://www.sportsuite.co.uk/a-z) module) remains the sole property of SportSuite at the present time, and I do not see value in providing our own scheme behind a paywall.

I will continue to leave this issue open for the benefit of other users of our feed, and to track any changes.

**Comment by nickevansuk** [comment]
@RoastVeg although it sounds like the SportSuite proprietary list might now have expanded (as other similar lists have done), presumably it is still possible to maintain a mapping of each activity in your internal list to the relevant activity in the OpenActive list, as other booking systems do?

Some systems do this by just adding an extra field to their internal activity list table containing the OpenActive Activity List id, to allow them to output that in the feed, for example.

The key thing here is to make the open data usable by ensuring OpenActive Activity List references are included, rather than exposing the proprietary list. Of course you would still be welcome to join the [OpenActive Activity List Committee](https://www.openactive.io/activity-list/), or contribute new activities there, if that was of interest - however this is by no means a prerequisite for maintaining a mapping.

Also worth noting that for instances where a direct mapping does not exist, you can map to the nearest activity or the relevant parent activity in the hierarchy - assuming you'd prefer not to contribute to the open list.

**Comment by domfennell** [comment]
Hi @RoastVeg, hope you're staying safe and keeping well!

Did you have any thoughts on @nickevansuk feedback from last week?

**Comment by domfennell** [comment]
HI @RoastVeg, thanks for sorting the [HTML tags issue](https://github.com/cuttlefishers/opendata/issues/10).

Any progress with ensuring OpenActive Activity List references are included?

**Comment by RoastVeg** [comment]
This issue is now resolved.

**Comment by domfennell** [comment]
Thanks, @RoastVeg!
