### ISSUE TITLE
Some descriptions include HTML tags

### ISSUE THREAD

**Issue by domfennell** [cuttlefishers/opendata#10]
Hi @RoastVeg,

I noticed that some descriptions in the feed contain HMTL tags. These appear in our API and will subsequently appear on the front end activity finders, which doesn't look great.

There are two types of descriptions in the OpenActive documentation:

- `description`; and
- `beta:formattedDescription` (found in [Beta OpenActive Namespace Vocabulary Terms](https://www.openactive.io/ns-beta/)) - it is my understanding that this is where any HTML should go.

Best,

Dom

**Comment by nickevansuk** [comment]
Just adding to this while I'm here, if helpful...

Generally using [strip_tags](https://www.php.net/manual/en/function.strip-tags.php) or similar to populate the `description` works well, while also providing the formatted string in `beta:formattedDescription` for those data consumers that can read the HTML.

See also guidance for both of these here: https://developer.openactive.io/data-model/types/sessionseries

**Comment by RoastVeg** [comment]
Could you please give the @id of somewhere where a description contains html tags? I noticed that some fields contained html entities which will be removed.

**Comment by domfennell** [comment]
`SessionSeries` with `"id": "417171"`, which appears in [this page](https://www.sportsuite.co.uk/api/cs-api/openactive?afterTimestamp=1583251654&afterId=414563) of the feed, has the following `organizer.description`:

`"description": "Juanita has run keep fit classes for over 13 years.\r\nProviding mostly activities for over 50's, health and well being interventions.\r\nIncluding falls preventing\r\nStroke, cancer and arthritis rehab.\r\nProvides school days demonstration, exhibitions (to incl",`

My apologies if these are html entities as opposed to html tags; a misunderstanding on my part.

**Comment by RoastVeg** [comment]
Those are neither HTML entities nor HTML tags - they are escaped line feeds. I will remove those in due course.

**Comment by domfennell** [comment]
Yes, sorry. @nickevansuk said that `\r\n` is plain text for “new line”, so isn’t HTML. Apologies for any confusion caused.

**Comment by RoastVeg** [comment]
This issue is now resolved
