### ISSUE TITLE
Empty strings and zero durations

### ISSUE THREAD

**Issue by nickevansuk** [cuttlefishers/opendata#12]
Just picking up on some additional validation issues where empty strings and included in the feed.

https://validator.openactive.io/?url=https%3A%2F%2Fwww.sportsuite.co.uk%2Fapi%2Fcs-api%2Fopenactive&version=2.0&validationMode=RPDEFeed

Please note that properties must be omitted when they contain empty strings.

Additionally the `endDate` and `duration` must be omitted when the duration is zero (as an event cannot have a zero duration, so rendering these properties would be inaccurate).

**Comment by nickevansuk** [comment]
Also note the OpenActive libraries solve the empty string issue for you, if that's helpful: https://developer.openactive.io/publishing-data/data-feeds/implementing-rpde-feeds#net-php-and-ruby-libraries

**Comment by jonferguson** [comment]
These issues have now been fixed.
