### ISSUE TITLE
Session title is erroneously included in the location name

### ISSUE THREAD

**Issue by domfennell** [cuttlefishers/opendata#13]
The `data.location.name` field feed appears to be duplicating the data included at `data.name`. This means that the place name is the name of the session rather than the name of the place. Having eyeballed the data in the feed, this appears impacts a large number of items in the feed. Two examples of this are:

```
"location": {
"@id": "https://www.sportsuite.co.uk/guid/activity/p/14296",
"name": "South Leicestershire Badminton Junior Club - 6:00pm to 7:30pm season 2020/21 sessions",
```

```
"location": {
"@id": "https://www.sportsuite.co.uk/guid/activity/p/377408",
"name": "Thurrock Thameside Nature Reserve Work Party",
```

**Comment by jonferguson** [comment]
We've now removed the session title in the location name.
