### ISSUE TITLE
Required property `name` is missing from `Place`

### ISSUE THREAD

**Issue by domfennell** [cuttlefishers/opendata#15]
When the feed is put into [the OpenActive Data Model Validator](https://data-model-validator.herokuapp.com/?url=https%3A%2F%2Fwww.sportsuite.co.uk%2Fapi%2Fcs-api%2Fopenactive&version=2.0&validationMode=RPDEFeed), an error with error message is returned for item with id `11009` in the feed: "Required property `name` is missing from `Place`". The location object is as follows for this item:

```
"location": {
"geo": {
"latitude": 51.49625266,
"longitude": -0.57343404,
"@type": "GeoCoordinates"
},
"@type": "Place"
},
```

The Spec. notes [here](https://openactive.io/modelling-opportunity-data/#describing-locations-code-schema-place-code-) that `data.location.name` is a required property. For the item at fault (and any other sessions with this issue), it will not be possible to tell where exactly the session takes place.

**Comment by jonferguson** [comment]
This has now been fixed.
