### ISSUE TITLE
No Offers in datafeed

### ISSUE THREAD

**Issue by thill-odi** [cuttlefishers/opendata#2]
AFAICT there are no Offers associated with any of the Opportunities in the datafeed. The use of such Offers is recommended, even where Opportunities are free of charge, to assist in the discoverability and display of free Opportunities. Without Offer information, charging information may appear to be simply unknown, rather than free-of-charge.

**Comment by RoastVeg** [comment]
Offers are now shown for all activities

**Comment by thill-odi** [comment]
I think there's been a reversion: looking at https://www.sportsuite.co.uk/api/cs-api/openactive, Offers have disappeared again.

**Comment by RoastVeg** [comment]
Apologies, we had an internal regression. This should now be fixed.
