### ISSUE TITLE
Many objects missing IDs

### ISSUE THREAD

**Issue by thill-odi** [cuttlefishers/opendata#3]
OpenActive standards recommend the use of unique identifiers - ideally in the form of URIs - for numerous datafeed objects, to assist in their identification and deduplication. At the moment, objects in the Sportsuite datafeeds lack such IDs, in particular:

- Organizations
- Places
- Concepts
- ScheduledSessions

**Comment by RoastVeg** [comment]
Organizations now have `@id`s

All other types listed are still without for now

**Comment by RoastVeg** [comment]
This issue is now resolved
