### ISSUE TITLE
Places missing numerous RECOMMENDED attributes

### ISSUE THREAD

**Issue by thill-odi** [cuttlefishers/opendata#4]
At the moment, Places populating `schema:location` fields lack many RECOMMENDED attributes that would increase their utility for end users. In particular, they tend to be missing:

- `id`
- `url`
- `description`
- `image`
- `telephone`
- `openingHoursSpecification`
- `amenityFeature`

**Comment by RoastVeg** [comment]
Places now have `@id`s and where possible: `url`, `description`, and `telephone`
