### ISSUE TITLE
`activity` field missing RECOMMENDED information

### ISSUE THREAD

**Issue by thill-odi** [cuttlefishers/opendata#5]
The `activity` field is currently missing a couple of properties useful to data processors and consumers, in particular:

`id`
`inScheme`

Note further that the value of `id` ideally consists of an OpenActive Activity List identifier, as ### [described](https://github.com/cuttlefishers/opendata/issues/1) in Issue 1.

**Comment by RoastVeg** [comment]
Activity concepts now have `@id`s

**Comment by RoastVeg** [comment]
Activities now also, where applicable, have `inScheme`
