### ISSUE TITLE
'next' attribute missing from datafeed

### ISSUE THREAD

**Issue by thill-odi** [cuttlefishers/opendata#8]
Looking at https://www.sportsuite.co.uk/api/cs-api/openactive, there's no 'next' attribute to indicate how to page through to further data; even if there's only one page, according to the RPDE spec it should have a 'next' attribute (with the value being the URL of the page itself).

See here for more details: https://developer.openactive.io/guide-to-openactive-on-github/rpde

**Comment by RoastVeg** [comment]
The next attribute appears to be just fine, is there a specific page in the feed where it is not showing?

**Comment by thill-odi** [comment]
Apologies; my mistake entirely. Just failed to spot it.
