### ISSUE TITLE
Higher page size?

### ISSUE THREAD

**Issue by domfennell** [cuttlefishers/opendata#9]
Hi @RoastVeg,

Hope you're keeping safe and well!

We're looking forward to ingesting SportSuite data into our platform. We just had one request: would it be possible to please increase the page size?

It's currently set to 20, which means that it can take a very long time for crawlers (e.g. crawlers that use a cronjob) to get to the end of it. This means that SportSuite data in these aggregators will be less up to date.

RPDE suggests a higher page size of [500 items per page](https://www.w3.org/2017/08/realtime-paged-data-exchange/#modified-timestamp-and-id) as a default. You can implement this as a limit query parameter, i.e. an optional field in RPDE. e.g. `&limit=500`. Hopefully this is something that can be accommodated.

Very best,

Dom

**Comment by RoastVeg** [comment]
Hi @domfennell 
Increasing page size is something we are definitely considering, and combined with better removal of deleted entries in the RPDE feed will make parsing it much easier. This is a work in progress though.

**Comment by domfennell** [comment]
Great to hear it's a work in progress, @RoastVeg. Any idea when the implementation is likely to be completed?

Also, with regards to the deleted entries, do you know how long you keep these for/how many deleted items you have in the feed?

**Comment by RoastVeg** [comment]
This is now resolved

**Comment by domfennell** [comment]
Thanks, @RoastVeg. Much appreciated.
